const products = [
    {
        id: "ingrum",
        title: "Ingrun",
        price: "€90",
        size: "130x170 cm",
        color: "gray",
        description:
            "Wool is stain resistant. This wear-resistant material perfectly retains heat. You can wrap yourself up comfortably lying on the couch.",
        details: "Natural fibers, easy care, soft finish.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/ingrum.png",
            "shop/ingrum.png",
            "shop/ingrum.png",
            "shop/ingrum.png",
        ],
        thumbs: [
            "shop/ingrum.png",
            "shop/ingrum.png",
            "shop/ingrum.png",
            "shop/ingrum.png",
        ],
    },
    {
        id: "mialotta",
        title: "Mialotta",
        price: "€140",
        size: "130x170 cm",
        color: "orange",
        description:
            "Soft, pleasant to the touch chenille fabric. Polyester is used in the composition of the fabric, along with other materials.",
        details: "Synthetic blend, lightweight, cozy feel.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/mialota.png",
            "shop/mialota.png",
            "shop/mialota.png",
            "shop/mialota.png",
        ],
        thumbs: [
            "shop/mialota.png",
            "shop/mialota.png",
            "shop/mialota.png",
            "shop/mialota.png",
        ],
    },
    {
        id: "luddmalla",
        title: "Luddmalla",
        price: "€95",
        size: "130x170 cm",
        color: "gray",
        description: "Cozy blanket to keep you warm at home or outdoors.",
        details: "Soft-touch finish, easy to wash.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/ludmalla.png",
            "shop/ludmalla.png",
            "shop/ludmalla.png",
            "shop/ludmalla.png",
        ],
        thumbs: [
            "shop/ludmalla.png",
            "shop/ludmalla.png",
            "shop/ludmalla.png",
            "shop/ludmalla.png",
        ],
    },
    {
        id: "vivianna",
        title: "Vivianna",
        price: "€175",
        size: "120x180 cm",
        color: "cappuccino",
        description:
            "An acrylic blanket is just as soft, warm and cozy as a wool blanket. At the same time, it is very easy to care for.",
        details: "Easy care acrylic, warm and breathable.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/vivianna.png",
            "shop/vivianna.png",
            "shop/vivianna.png",
            "shop/vivianna.png",
        ],
        thumbs: [
            "shop/vivianna.png",
            "shop/vivianna.png",
            "shop/vivianna.png",
            "shop/vivianna.png",
        ],
    },
    {
        id: "evali",
        title: "Evali",
        price: "€90",
        size: "130x170 cm",
        color: "cappuccino",
        description: "Lightweight everyday throw for couch and bed.",
        details: "Natural blend, soft handfeel.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/evali.png",
            "shop/evali.png",
            "shop/evali.png",
            "shop/evali.png",
        ],
        thumbs: [
            "shop/evali.png",
            "shop/evali.png",
            "shop/evali.png",
            "shop/evali.png",
        ],
    },
    {
        id: "kersti",
        title: "Kersti",
        price: "€175",
        size: "150x200 cm",
        color: "orange",
        description:
            "Thick blanket that keeps warmth longer on chilly evenings.",
        details: "Natural fibers, durable weave.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/kersti.png",
            "shop/kersti.png",
            "shop/kersti.png",
            "shop/kersti.png",
        ],
        thumbs: [
            "shop/kersti.png",
            "shop/kersti.png",
            "shop/kersti.png",
            "shop/kersti.png",
        ],
    },
    {
        id: "helgun",
        title: "Helgun",
        price: "€135",
        size: "150x200 cm",
        color: "beige",
        description:
            "Wool is stain resistant. This wear-resistant material perfectly retains heat. You can wrap yourself up comfortably lying on the couch or throw it over yourself when it's cool.",
        details: "Natural wool mix, long-lasting quality.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/helgum.png",
            "shop/helgum_min1.png",
            "shop/helgum_min2.png",
            "shop/helgum_min3.png",
        ],
        thumbs: [
            "shop/helgum.png",
            "shop/helgum_min1.png",
            "shop/helgum_min2.png",
            "shop/helgum_min3.png",
        ],
    },
    {
        id: "dagnhild",
        title: "Dagnhild",
        price: "€150",
        size: "150x200 cm",
        color: "yellow-beige",
        description:
            "You can wrap yourself up comfortably lying on the couch or throw it over yourself when it's cool.",
        details: "Soft synthetic blend, easy care.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/dagnhild.png",
            "shop/dagnhild.png",
            "shop/dagnhild.png",
            "shop/dagnhild.png",
        ],
        thumbs: [
            "shop/dagnhild.png",
            "shop/dagnhild.png",
            "shop/dagnhild.png",
            "shop/dagnhild.png",
        ],
    },
    {
        id: "varkrage",
        title: "Varkrage",
        price: "€90",
        size: "110x170 cm",
        color: "red",
        description: "Compact throw for travel and quick warmth.",
        details: "Durable synthetic, bright color.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/varkrage.png",
            "shop/varkrage.png",
            "shop/varkrage.png",
            "shop/varkrage.png",
        ],
        thumbs: [
            "shop/varkrage.png",
            "shop/varkrage.png",
            "shop/varkrage.png",
            "shop/varkrage.png",
        ],
    },
    {
        id: "dablidun",
        title: "Dablidun",
        price: "€170",
        size: "150x200 cm",
        color: "red",
        description: "Warm and dense blanket for cold days.",
        details: "Synthetic fill, cozy texture.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/dadlidun.png",
            "shop/dadlidun.png",
            "shop/dadlidun.png",
            "shop/dadlidun.png",
        ],
        thumbs: [
            "shop/dadlidun.png",
            "shop/dadlidun.png",
            "shop/dadlidun.png",
            "shop/dadlidun.png",
        ],
    },
    {
        id: "ingabritta",
        title: "Ingabritta",
        price: "€120",
        size: "130x170 cm",
        color: "beige",
        description: "Textured weave that adds depth to your interior.",
        details: "Synthetic blend, lightweight.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/ingabrita.png",
            "shop/ingabrita.png",
            "shop/ingabrita.png",
            "shop/ingabrita.png",
        ],
        thumbs: [
            "shop/ingabrita.png",
            "shop/ingabrita.png",
            "shop/ingabrita.png",
            "shop/ingabrita.png",
        ],
    },
    {
        id: "ylvali",
        title: "Ylvali",
        price: "€110",
        size: "150x200 cm",
        color: "gray",
        description: "Everyday throw with a calm neutral tone.",
        details: "Synthetic blend, machine washable.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/yivali.png",
            "shop/yivali.png",
            "shop/yivali.png",
            "shop/yivali.png",
        ],
        thumbs: [
            "shop/yivali.png",
            "shop/yivali.png",
            "shop/yivali.png",
            "shop/yivali.png",
        ],
    },
    {
        id: "gerhild",
        title: "Gerhild",
        price: "€90",
        size: "130x170 cm",
        color: "gray",
        description: "Soft neutral blanket for everyday use.",
        details: "Synthetic blend, easy care.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "homepage/gerhild.png",
            "homepage/gerhild.png",
            "homepage/gerhild.png",
            "homepage/gerhild.png",
        ],
        thumbs: [
            "homepage/gerhild.png",
            "homepage/gerhild.png",
            "homepage/gerhild.png",
            "homepage/gerhild.png",
        ],
    },
    {
        id: "gultall",
        title: "Gultall",
        price: "€180",
        size: "130x170 cm",
        color: "yellow",
        description: "Bright accent throw to warm up any interior.",
        details: "Synthetic blend, soft touch.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "homepage/gultall.png",
            "homepage/gultall.png",
            "homepage/gultall.png",
            "homepage/gultall.png",
        ],
        thumbs: [
            "homepage/gultall.png",
            "homepage/gultall.png",
            "homepage/gultall.png",
            "homepage/gultall.png",
        ],
    },
    {
        id: "rovaror",
        title: "Rovaror",
        price: "€85",
        size: "150x200 cm",
        color: "gray",
        description: "Durable large blanket for everyday comfort.",
        details: "Synthetic blend, machine washable.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "homepage/rovaror.png",
            "homepage/rovaror.png",
            "homepage/rovaror.png",
            "homepage/rovaror.png",
        ],
        thumbs: [
            "homepage/rovaror.png",
            "homepage/rovaror.png",
            "homepage/rovaror.png",
            "homepage/rovaror.png",
        ],
    },
    {
        id: "ulltistel",
        title: "Ulltistel",
        price: "€150",
        size: "130x170 cm",
        color: "beige",
        description: "Cozy plaid that keeps you warm on cool evenings.",
        details: "Natural wool blend, soft texture.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/ulltistel.png",
            "shop/ulltistel.png",
            "shop/ulltistel.png",
            "shop/ulltistel.png",
        ],
        thumbs: [
            "shop/ulltistel.png",
            "shop/ulltistel.png",
            "shop/ulltistel.png",
            "shop/ulltistel.png",
        ],
    },
    {
        id: "gulklint",
        title: "Gulklint",
        price: "€175",
        size: "150x200 cm",
        color: "yellow",
        description: "Warm blanket with a bright pattern.",
        details: "Synthetic blend, soft and durable.",
        delivery: "Standard delivery 3-5 days.",
        images: [
            "shop/gulklint.png",
            "shop/gulklint.png",
            "shop/gulklint.png",
            "shop/gulklint.png",
        ],
        thumbs: [
            "shop/gulklint.png",
            "shop/gulklint.png",
            "shop/gulklint.png",
            "shop/gulklint.png",
        ],
    },
];

export default products;
